(executable
 (name emo_project_test)
 (libraries alcotest unix emo_pkg emo_project emo_support emo_eval))

(rule
 (alias runtest)
 (deps
  (source_tree ../../examples)
  (source_tree ../../stdlib)
  emo_project_test.exe)
 (action
  (setenv
   EMO_EXAMPLES_DIR
   %{workspace_root}/examples
   (run %{exe:emo_project_test.exe}))))
