(* generated by emo build — do not edit *)

let rec sp_main__count_down (v_n : int) : int =
(let exception Native_return of int in
(try (if (v_n = 0) then
(let _ = ((raise (Native_return 0))) in
sp_main__count_down (v_n - 1))
else
(let _ = (()) in
sp_main__count_down (v_n - 1))) with Native_return v -> v))

and sp_main__fib (v_n : int) : int =
(let exception Native_return of int in
(try (if (v_n < 2) then
(let _ = ((raise (Native_return v_n))) in
(sp_main__fib (v_n - 1) + sp_main__fib (v_n - 2)))
else
(let _ = (()) in
(sp_main__fib (v_n - 1) + sp_main__fib (v_n - 2)))) with Native_return v -> v))

let main__count_down (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_n ] ->
    Emo_runtime.box_int (sp_main__count_down (Emo_runtime.unbox_int v_n))
  | _ -> Emo_runtime.arity_error "main__count_down" 1 (List.length args)

let main__fib (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_n ] ->
    Emo_runtime.box_int (sp_main__fib (Emo_runtime.unbox_int v_n))
  | _ -> Emo_runtime.arity_error "main__fib" 1 (List.length args)


let rec __nothing (args : Emo_eval.value list) : Emo_eval.value =
    Emo_eval.Int 0

(* interfaces *)

(* class method tables *)


let () =
  let exit_code =
    Emo_runtime.run (fun () ->
  let v_greeting = (Emo_eval.CompiledFn { Emo_eval.fdesc = "<block>"; farity = 1; fapply = fun args -> (match args with [ v_name ] -> (try Emo_runtime.interpolate [Emo_eval.String "hello, "; v_name] with Emo_runtime.Return_signal v -> v) | _ -> Emo_runtime.arity_error "<block>" 1 (List.length args)) }) in
  let _ = Emo_eval.call_builtin "print" [main__fib [Emo_eval.Int 20]] in
  let _ = Emo_eval.call_builtin "print" [Emo_runtime.apply_value v_greeting [Emo_eval.String "emo"]] in
  ignore (Emo_eval.call_builtin "print" [main__count_down [Emo_eval.Int 1000000]])
)
  in
  if exit_code <> 0 then exit exit_code
