(* generated by emo build — do not edit *)


let rec main__welcome (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_g ] ->
    (try
  (Emo_runtime.method_call (v_g) "greet" [])
with Emo_runtime.Return_signal v -> v)
  | _ -> Emo_runtime.arity_error "main__welcome" 1 (List.length args)
and main__English__greet (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_self ] ->
    (try
  Emo_eval.String "Hello"
with Emo_runtime.Return_signal v -> v)
  | _ -> Emo_runtime.arity_error "main__English__greet" 1 (List.length args)
and main__User__init (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_self; v_name; v_age ] ->
    (try
  let _ = Emo_runtime.obj_set_field v_self "name" v_name in
  (Emo_runtime.obj_set_field v_self "age" v_age;
  Emo_eval.Int 0)
with Emo_runtime.Return_signal v -> v)
  | _ -> Emo_runtime.arity_error "main__User__init" 3 (List.length args)
and main__User__full_name (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_self ] ->
    (try
  (Emo_runtime.add ((Emo_runtime.add ((Emo_runtime.add ((Emo_runtime.field (v_self) "name")) (Emo_eval.String " ("))) ((Emo_runtime.method_call ((Emo_runtime.field (v_self) "age")) "to_string" [])))) (Emo_eval.String ")"))
with Emo_runtime.Return_signal v -> v)
  | _ -> Emo_runtime.arity_error "main__User__full_name" 1 (List.length args)
and main__User__is_older_q (args : Emo_eval.value list) : Emo_eval.value =
  match args with
  | [ v_self ] ->
    (try
  (Emo_runtime.gt ((Emo_runtime.field (v_self) "age")) (Emo_eval.Int 35))
with Emo_runtime.Return_signal v -> v)
  | _ -> Emo_runtime.arity_error "main__User__is_older_q" 1 (List.length args)

(* interfaces *)
let () = Emo_runtime.register_interface "Greeter" [("greet", 0)]

(* class method tables *)
let __methods_main__English : (string, int * (Emo_eval.value list -> Emo_eval.value)) Hashtbl.t = Hashtbl.create 8
let __methods_main__User : (string, int * (Emo_eval.value list -> Emo_eval.value)) Hashtbl.t = Hashtbl.create 8

let () =
  Hashtbl.replace __methods_main__English "greet" (0, fun args -> main__English__greet ([] @ args));
()

let () =
  Hashtbl.replace __methods_main__User "full_name" (0, fun args -> main__User__full_name ([] @ args));
  Hashtbl.replace __methods_main__User "is_older?" (0, fun args -> main__User__is_older_q ([] @ args));
()


let main__English__new (args : Emo_eval.value list) : Emo_eval.value =
  let self = Emo_eval.Obj (Emo_runtime.new_obj "English" __methods_main__English) in
  
  self

let main__User__new (args : Emo_eval.value list) : Emo_eval.value =
  let self = Emo_eval.Obj (Emo_runtime.new_obj "User" __methods_main__User) in
  let (_ : Emo_eval.value) = main__User__init (self :: args) in
  self

let () =
  let exit_code =
    Emo_runtime.run (fun () ->
  let v_u = main__User__new [Emo_eval.String "Ada"; Emo_eval.Int 36] in
  let _ = Emo_eval.call_builtin "print" [(Emo_runtime.method_call (v_u) "full_name" [])] in
  let _ = Emo_eval.call_builtin "print" [(Emo_runtime.method_call (v_u) "is_older?" [])] in
  let _ = Emo_eval.call_builtin "print" [(Emo_runtime.eq (v_u) (main__User__new [Emo_eval.String "Ada"; Emo_eval.Int 36]))] in
  let _ = Emo_eval.call_builtin "print" [(Emo_runtime.eq (Emo_eval.EnumMember ("Color", "red")) (Emo_eval.EnumMember ("Color", "red")))] in
  let _ = Emo_eval.call_builtin "print" [main__welcome [main__English__new []]] in
  ignore (Emo_eval.call_builtin "print" [(Emo_runtime.method_call (main__English__new []) "is" [Emo_eval.TypeValue "Greeter"])])
)
  in
  if exit_code <> 0 then exit exit_code
