(* generated by emo build — do not edit *)


let rec __nothing (args : Emo_eval.value list) : Emo_eval.value =
    Emo_eval.Int 0

(* interfaces *)

(* class method tables *)


let () =
  let exit_code =
    Emo_runtime.run (fun () ->
  ignore (Emo_eval.call_builtin "print" [Emo_eval.String "Hello, world!"])
)
  in
  if exit_code <> 0 then exit exit_code
